import customtkinter as ctk

from src.analysis import BoardUtils
from src.analysis.Unit import Unit
from src.core.Move import Move, ValueChangeMove
from src.render.components.core.SudokuGrid import SudokuGrid

class Step:
    def __init__(self, text: str):
        self.text = text

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        infoLabel.configure(text=self.text)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        pass

# Note for Steps, always place the text to be shown in the last step's text value Every other text value can be empty.
class Steps(Step):
    def __init__(self, steps: list[Step]) -> None:
        self.steps = steps

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        for step in self.steps:
            step.apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        for step in reversed(self.steps):
            step.undo(renderer, infoLabel)

class ShowText(Step):
    pass

class HighlightCells(Step):
    def __init__(self, text: str, positionsOrUnit: list[tuple[int, int]] | Unit, colour: str = "#FCFC76"):
        super().__init__(text)
        self.colour = colour

        if type(positionsOrUnit) is list:
            self.cells = positionsOrUnit
        elif type(positionsOrUnit) is Unit:
            self.cells = [positionsOrUnit.getBoardPosition(i) for i in range(9)]

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        renderer.highlightCells(self.cells, self.colour)
        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        renderer.highlightCells(self.cells, "white")
        return super().undo(renderer, infoLabel)

class PopulateCandidatesInCells(Step):
    def __init__(self, text: str, positionsOrUnit: list[tuple[int, int]] | Unit):
        super().__init__(text)
        if type(positionsOrUnit) is list:
            self.cells = positionsOrUnit
        elif type(positionsOrUnit) is Unit:
            self.cells = [positionsOrUnit.getBoardPosition(i) for i in range(9)]

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        board = renderer.boardState
        candidates = BoardUtils.getCandidatesMatrix(board)

        for row, col in self.cells:
            board.getCell(row, col).addCandidates(candidates[row][col])
            renderer.redrawCell(row, col)

        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        board = renderer.boardState
        candidates = BoardUtils.getCandidatesMatrix(board)

        for row, col in self.cells:
            board.getCell(row, col).removeCandidates(candidates[row][col])
            renderer.redrawCell(row, col)

        return super().undo(renderer, infoLabel)

# Class PopulateAllCandidates was generated by ChatGPT. https://chatgpt.com/share/6ab5784f-3268-83eb-9e00-93a60725a152
# Prompt: "IS there some way i can make a shorthand for this when covering the entire board state, maybe another step class like PopulateAllCandidates?"
class PopulateAllCandidates(PopulateCandidatesInCells):
    def __init__(self, text: str):
        super().__init__(
            text,
            [(row, col) for row in range(9) for col in range(9)]
        )

class UpdateCellValue(Step):
    def __init__(self, text: str, row: int, col: int, digit: int | None):
        self.move = ValueChangeMove(row, col, digit)
        super().__init__(text)

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        self.move.apply(renderer.boardState)
        renderer.redraw()
        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        self.move.undo(renderer.boardState)
        renderer.redraw()
        return super().undo(renderer, infoLabel)