import customtkinter as ctk

from src.analysis import BoardUtils
from src.analysis.Unit import Unit
from src.core.Move import Move, ValueChangeMove
from src.render.components.core.SudokuGrid import SudokuGrid

class Step:
    def __init__(self, text: str, stackable: bool = False):
        self.text = text
        self.stackable = stackable

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        if len(self.text) > 0:
            infoLabel.configure(text=self.text)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        pass

# Note for Steps, always place the text to be shown in the last step's text value Every other text value can be empty.
class Steps(Step):
    def __init__(self, steps: list[Step], stackable: bool = False) -> None:
        self.steps = steps
        self.stackable = stackable

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        for step in self.steps:
            step.apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        for step in reversed(self.steps):
            step.undo(renderer, infoLabel)

class ShowText(Step):
    pass

class HighlightCells(Step):
    def __init__(self, text: str, positionsOrUnit: list[tuple[int, int]] | Unit, colour: str = "#FCFC76", stackable: bool = False):
        super().__init__(text, stackable)
        self.colour = colour

        if type(positionsOrUnit) is list:
            self.cells = positionsOrUnit
        elif type(positionsOrUnit) is Unit:
            self.cells = [positionsOrUnit.getBoardPosition(i) for i in range(9)]

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        renderer.highlightCells(self.cells, self.colour)
        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        renderer.highlightCells(self.cells, "white")
        return super().undo(renderer, infoLabel)

class PopulateLogicalCandidatesInCells(Step):
    def __init__(self, text: str, positionsOrUnit: list[tuple[int, int]] | Unit, stackable: bool = False):
        super().__init__(text, stackable)
        if type(positionsOrUnit) is list:
            self.cells = positionsOrUnit
        elif type(positionsOrUnit) is Unit:
            self.cells = [positionsOrUnit.getBoardPosition(i) for i in range(9)]

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        board = renderer.boardState
        candidates = BoardUtils.getCandidatesMatrix(board)

        for row, col in self.cells:
            board.getCell(row, col).addCandidates(candidates[row][col])
            renderer.redrawCell(row, col)

        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        board = renderer.boardState
        candidates = BoardUtils.getCandidatesMatrix(board)

        for row, col in self.cells:
            board.getCell(row, col).removeCandidates(candidates[row][col])
            renderer.redrawCell(row, col)

        return super().undo(renderer, infoLabel)

class PopulateEveryCandidateNumberInCells(Step):
    ALL_CANDIDATES = {1,2,3,4,5,6,7,8,9}

    def __init__(self, text: str, positionsOrUnit: list[tuple[int, int]] | Unit, stackable: bool = False):
        super().__init__(text, stackable)
        if type(positionsOrUnit) is list:
            self.cells = positionsOrUnit
        elif type(positionsOrUnit) is Unit:
            self.cells = [positionsOrUnit.getBoardPosition(i) for i in range(9)]
    
    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        board = renderer.boardState

        for row, col in self.cells:
            board.getCell(row, col).addCandidates(self.ALL_CANDIDATES)
            renderer.redrawCell(row, col)

        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        board = renderer.boardState

        for row, col in self.cells:
            board.getCell(row, col).removeCandidates(self.ALL_CANDIDATES)
            renderer.redrawCell(row, col)

        return super().undo(renderer, infoLabel)

# Class PopulateAllCandidates was generated by ChatGPT. https://chatgpt.com/share/6ab5784f-3268-83eb-9e00-93a60725a152
# Prompt: "IS there some way i can make a shorthand for this when covering the entire board state, maybe another step class like PopulateAllCandidates?"
class PopulateAllLogicalCandidates(PopulateLogicalCandidatesInCells):
    def __init__(self, text: str, stackable: bool = False):
        super().__init__(
            text,
            [(row, col) for row in range(9) for col in range(9)],
            stackable
        )

class ApplyMove(Step):
    def __init__(self, text: str, move: Move, stackable: bool = False):
        self.move = move
        super().__init__(text, stackable)

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        self.move.apply(renderer.boardState)
        renderer.redraw()
        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        self.move.undo(renderer.boardState)
        renderer.redraw()
        return super().undo(renderer, infoLabel)

class ApplyMoves(Step):
    def __init__(self, text: str, moves: list[Move], stackable: bool = False):
        self.moves = moves
        super().__init__(text, stackable)

    def apply(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        for move in self.moves:
            move.apply(renderer.boardState)
        renderer.redraw()
        return super().apply(renderer, infoLabel)

    def undo(self, renderer: SudokuGrid, infoLabel: ctk.CTkLabel):
        for move in reversed(self.moves):
            move.undo(renderer.boardState)
        renderer.redraw()
        return super().undo(renderer, infoLabel)